server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:6543/ewm
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  sql:
    init:
      mode: always
      platform: postgresql
      schema-locations: classpath:schema.sql

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}