x-db-common: &db-common
  image: postgres:16.1
  restart: unless-stopped
  networks:
    - ewm-network

services:

  stats-db:
    <<: *db-common
    container_name: stats-db
    environment:
      POSTGRES_DB: ewm-stats
      POSTGRES_USER: stat
      POSTGRES_PASSWORD: stat
    ports:
      - "5433:5432"
    volumes:
      - stats-db-data:/var/lib/postgresql/data

  user-db:
    <<: *db-common
    container_name: user-db
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5435:5432"

  rating-db:
    <<: *db-common
    container_name: rating-db
    environment:
      POSTGRES_DB: rating
      POSTGRES_USER: rating
      POSTGRES_PASSWORD: rating
    ports:
      - "5436:5432"

  request-db:
    <<: *db-common
    container_name: request-db
    environment:
      POSTGRES_DB: request
      POSTGRES_USER: request
      POSTGRES_PASSWORD: request
    ports:
      - "5437:5432"

  event-db:
    <<: *db-common
    container_name: event-db
    environment:
      POSTGRES_DB: event
      POSTGRES_USER: event
      POSTGRES_PASSWORD: event
    ports:
      - "5434:5432"

networks:
  ewm-network:
    driver: bridge

volumes:
  stats-db-data: