x-db-common: &db-common
  image: postgres:16.1
  restart: unless-stopped
  networks:
    - ewm-network

services:

  stats-db:
    <<: *db-common
    container_name: stats-db
    environment:
      POSTGRES_DB: ewm-stats
      POSTGRES_USER: stat
      POSTGRES_PASSWORD: stat
    ports:
      - "5433:5432"

  user-db:
    <<: *db-common
    container_name: user-db
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5435:5432"

  rating-db:
    <<: *db-common
    container_name: rating-db
    environment:
      POSTGRES_DB: rating
      POSTGRES_USER: rating
      POSTGRES_PASSWORD: rating
    ports:
      - "5436:5432"

  request-db:
    <<: *db-common
    container_name: request-db
    environment:
      POSTGRES_DB: request
      POSTGRES_USER: request
      POSTGRES_PASSWORD: request
    ports:
      - "5437:5432"

  event-db:
    <<: *db-common
    container_name: event-db
    environment:
      POSTGRES_DB: event
      POSTGRES_USER: event
      POSTGRES_PASSWORD: event
    ports:
      - "5434:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    restart: unless-stopped
    networks:
      - ewm-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    networks:
      - ewm-network
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    container_name: schema-registry
    restart: unless-stopped
    depends_on:
      - kafka
    networks:
      - ewm-network
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092

networks:
  ewm-network:
    driver: bridge

volumes:
  stats-db-data: