server:
  port: 0

spring:
  application:
    name: stats-server

  datasource:
    url: jdbc:postgresql://localhost:6542/stats
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true