server:
  port: 0

spring:
  kafka:
    bootstrap-servers: localhost:9092

    properties:
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true

    consumer:
      group-id: aggregator.group
      auto-offset-reset: earliest
      enable-auto-commit: false

      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

logging:
  level:
    root: INFO
    ru.practicum.stats.aggregator: DEBUG

app:
  kafka:
    topics:
      users: stats.user-actions.v1
      events: stats.events-similarity.v1

action-weights:
  view: 0.4
  register: 0.8
  like: 1.0